apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xzag3rhqy-nodejs 
  janus-idp.io/tekton: xzag3rhqy-nodejs
  backstage.io/kubernetes-id: xzag3rhqy-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xzag3rhqy-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  