apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xzag3rhqy-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xzag3rhqy-nodejs 
  name: xzag3rhqy-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xzag3rhqy-nodejs 
