apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xzag3rhqy-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:1dc2c6fcef09ac43b0a221fd35fc1e576224c581@sha256:37e14a0fe64a2771564703818a3e3549ec9eaeb756bd2fe97d5eb94992a3a1c1
          name: container-image
